apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  selector: # connects the Service and the Deployment
    app: nginx
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
